---
# ansible-playbook -u lookup project/mysql.yml --extra-vars 'target=rscx'
- hosts: '{{target}}'
  vars:
    rvm1_rubies: ['2.1.3']
    rvm1_install_flags: '--auto-dotfiles --user-install'
    app_path: '/data/{{ansible_user_id}}/app'
    rvm1_install_path: '/data/{{ansible_user_id}}/.rvm'
    db_password: "{{ lookup('password', playbook_dir + '/../credentials/' + inventory_hostname + '/' + ansible_user_id + '_mongodb length=15') }}"
  vars_files:
    - "{{playbook_dir}}/../../db.yml"
  roles:
    - { role: rvm1-ruby }
    - { role: mysql }
    - { role: env }
